; Each new term in the Fibonacci sequence is generated by adding
; the previous two terms. By starting with 1 and 2, the first 10
; terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values
; do not exceed four million, find the sum of the even-valued terms.

; 1+2+3+5+8 = 19
; 1+2+3+4+5 = 15

(prn "Problem 2")

;(->>
;  (concat `(1 2) `(3 4))
;  (prn))
;
;(->>
;  (concat `(1 4) (conj `() 5))
;  (prn))

;(dotimes [n 5]
;  (->>
;    (concat `(1 4) (conj `() 5))
;    (prn)
;    ))

;(->>
;  (range 10)
;  (map inc)
;  (map + first)
;  (prn)
;  )

(prn
  (loop [sum (conj `() `(2 3) `(1 2) `(1 1)) cnt 3]
    (if (= cnt 10)
      sum
      (recur
        (concat sum
          (conj `()
            (conj `()
              (+
                (second
                  (nth sum (- cnt 1)))
                (second
                  (nth sum (- cnt 2))))
              (second
                (nth sum (- cnt 2)))
              )))
        (inc cnt)
        )))
  )