; Each new term in the Fibonacci sequence is generated by adding
; the previous two terms. By starting with 1 and 2, the first 10
; terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values
; do not exceed four million, find the sum of the even-valued terms.
; Answer = 4613732

; This works... BUT IS VERY UGLY. TODO refactor
(->>
  (loop [sum (conj `() `(2 2 0) `(2 1 0) `(0 1 1)) cnt 3]
    (if (or (= cnt 40) (> (second (last sum)) 4000000))
      sum
      (let [n_minus_one_middle (second (nth sum (- cnt 1)))
            n_minus_two_middle (second (nth sum (- cnt 2)))
            n_minus_one_last (nth (nth sum (- cnt 1)) 2)]
        (recur
          (concat sum
            (conj `()
              (conj `()
                (if (even? n_minus_one_middle) (+ n_minus_one_last n_minus_one_middle) n_minus_one_last)
                (+ n_minus_one_middle n_minus_two_middle)
                n_minus_two_middle
                )
              )
            )
          (inc cnt)
          )
        )
      )
    )
  (last)
  (last)
  (prn)
  )